### ISSUE TITLE
Editor readonly mode not working

### ISSUE THREAD

**Issue by HDShabe** [balmjs/balm-ui#172]
- BalmUI version: 10.21.2

Hi @elf-mouse ,

I've got an editor that i'm using but it doesn't seem to be going into readonly mode properly. 

```

     <ui-editor v-model="viewModel.description"
                               placeholder="Description"
                               :readonly="fieldsLockedInEditMode"></ui-editor>
```

```
  computed: {
            fieldsLockedInEditMode() {
                return !this.editMode;
            }
        },
```

I can see in Vue dev tools it's setting the property fine, but UI still allows for edit.

![image](https://github.com/balmjs/balm-ui/assets/42472545/c3c1a584-97d5-4b6b-ba7a-572006ec099a)
![image](https://github.com/balmjs/balm-ui/assets/42472545/0a26ed13-e8b8-47ae-ab17-06ffb074d513)

**Comment by elf-mouse** [comment]
This bug has been fixed in the new version. Thanks.

**Comment by HDShabe** [comment]
Hi @elf-mouse 
I've updated to 10.22.0 but i'm still seeing the same behaviour, looking at your commit I don't think there's anything that I needed to change on my end?

**Comment by elf-mouse** [comment]
Hi @HDShabe , The `readonly` watch bug has been fixed. You can reinstall and try it again.

Thank you very much~

**Comment by HDShabe** [comment]
Looks much better, thanks again!

**Comment by HDShabe** [comment]
Hi @elf-mouse  

I've spotted something else. When I have the editor not rendered in a v-if and then change the state to render it, I'm getting a case where both the bound data and the placeholder are displaying at the same time.

![image](https://github.com/balmjs/balm-ui/assets/42472545/cd219fa0-5cd3-4a31-9a0d-0612f3868217)

![image](https://github.com/balmjs/balm-ui/assets/42472545/8fc6a133-6199-4a01-8685-4bf1c7536c25)

if I toggle readonly off then the placeholder disappears, from which point it seems to work as expected both in readonly and normal mode.

Cheers

**Comment by HDShabe** [comment]
Looking into this a little more, it only seems to happen when I have my ui-editor bound to a nested viewmodel on the data of the component, though i'm now seeing errors like this one after removing the viewmodel and binding ui-editor directly to the data object:

![image](https://github.com/balmjs/balm-ui/assets/42472545/70024e95-dbb9-4c6b-83cb-b34be787ff82)

I haven't got any conditional rendering other than the element sliding into the page with a CSS keyframe animation

**Comment by elf-mouse** [comment]
Hi @HDShabe , the `placeholder` bug has been fixed in new version. You can try it again. Thank you very much~
